const braille = [
    { name: "a(1)", img: require('../assets/grade 1/a.png') },
    { name: "b(2)", img: require('../assets/grade 1/b.png') },
    { name: "c(3)", img: require('../assets/grade 1/c.png') },
    { name: "d(4)", img: require('../assets/grade 1/d.png') },
    { name: "e(5)", img: require('../assets/grade 1/e.png') },
    { name: "f(6)", img: require('../assets/grade 1/f.png') },
    { name: "g(7)", img: require('../assets/grade 1/g.png') },
    { name: "h(8)", img: require('../assets/grade 1/h.png') },
    { name: "i(9)", img: require('../assets/grade 1/i.png') },
    { name: "j(0)", img: require('../assets/grade 1/j.png') },
    { name: "k", img: require('../assets/grade 1/k.png') },
    { name: "l", img: require('../assets/grade 1/l.png') },
    { name: "m", img: require('../assets/grade 1/m.png') },
    { name: "n", img: require('../assets/grade 1/n.png') },
    { name: "o", img: require('../assets/grade 1/o.png') },
    { name: "p", img: require('../assets/grade 1/p.png') },
    { name: "q", img: require('../assets/grade 1/q.png') },
    { name: "r", img: require('../assets/grade 1/r.png') },
    { name: "s", img: require('../assets/grade 1/s.png') },
    { name: "t", img: require('../assets/grade 1/t.png') },
    { name: "u", img: require('../assets/grade 1/u.png') },
    { name: "v", img: require('../assets/grade 1/v.png') },
    { name: "w", img: require('../assets/grade 1/w.png') },
    { name: "x", img: require('../assets/grade 1/x.png') },
    { name: "y", img: require('../assets/grade 1/y.png') },
    { name: "z", img: require('../assets/grade 1/z.png') },
]

export default braille;
